In [ ]:
import pandas as pd
df=pd.read_csv('bonus_dataset.csv')
import torch 

In [10]:
df.head()


employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [8]:
type(df['performance'].values)

numpy.ndarray

In [13]:
performance=torch.tensor(df['performance'].values,dtype=torch.float32)
years_of_exp=torch.tensor(df['years_of_experience'].values,dtype=torch.float32)
project_completed=torch.tensor(df['projects_completed'].values,dtype=torch.float32)
bonus=torch.tensor(df['bonus'].values,dtype=torch.float32)

In [15]:
w1=torch.rand(1,requires_grad=True)
w2=torch.rand(1,requires_grad=True)
w3=torch.rand(1,requires_grad=True)
bias=torch.rand(1,requires_grad=True)

w1,w2,w3,bias


(tensor([0.6335], requires_grad=True),
 tensor([0.4103], requires_grad=True),
 tensor([0.0473], requires_grad=True),
 tensor([0.1033], requires_grad=True))

In [29]:
w1 = torch.rand(1, requires_grad=True)
w2 = torch.rand(1, requires_grad=True)
w3 = torch.rand(1, requires_grad=True)
bias = torch.rand(1, requires_grad=True)

# Learning rate and number of iterations
learning_rate = 0.006
epochs = 5000

# Step 3: Training loop for gradient descent
for epoch in range(epochs):
    # Compute the predicted bonus using the current weights and bias
    predicted_bonus = w1 * performance + w2 * years_of_exp + w3 * project_completed + bias
    
    # Compute the Mean Squared Error (MSE) loss
    loss = ((predicted_bonus - bonus) ** 2).mean()
    
    # Perform backpropagation to compute gradients of the loss with respect to w1, w2, w3, and bias
    loss.backward()
    
    # Update the weights and bias using the computed gradients
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w3 -= learning_rate * w3.grad
        bias -= learning_rate * bias.grad

    # Zero the gradients after updating
    w1.grad.zero_()
    w2.grad.zero_()
    w3.grad.zero_()
    bias.grad.zero_()

    # Print the loss at regular intervals
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/5000], Loss: 17.8469
Epoch [200/5000], Loss: 15.5678
Epoch [300/5000], Loss: 13.5844
Epoch [400/5000], Loss: 11.8551
Epoch [500/5000], Loss: 10.3463
Epoch [600/5000], Loss: 9.0296
Epoch [700/5000], Loss: 7.8805
Epoch [800/5000], Loss: 6.8777
Epoch [900/5000], Loss: 6.0025
Epoch [1000/5000], Loss: 5.2386
Epoch [1100/5000], Loss: 4.5720
Epoch [1200/5000], Loss: 3.9902
Epoch [1300/5000], Loss: 3.4824
Epoch [1400/5000], Loss: 3.0392
Epoch [1500/5000], Loss: 2.6525
Epoch [1600/5000], Loss: 2.3149
Epoch [1700/5000], Loss: 2.0203
Epoch [1800/5000], Loss: 1.7632
Epoch [1900/5000], Loss: 1.5389
Epoch [2000/5000], Loss: 1.3430
Epoch [2100/5000], Loss: 1.1721
Epoch [2200/5000], Loss: 1.0230
Epoch [2300/5000], Loss: 0.8928
Epoch [2400/5000], Loss: 0.7792
Epoch [2500/5000], Loss: 0.6800
Epoch [2600/5000], Loss: 0.5935
Epoch [2700/5000], Loss: 0.5180
Epoch [2800/5000], Loss: 0.4520
Epoch [2900/5000], Loss: 0.3945
Epoch [3000/5000], Loss: 0.3443
Epoch [3100/5000], Loss: 0.3005
Epoch [3200/

In [30]:
w1.item(),w2.item(),w3.item(),bias.item()

(12.027344703674316, 5.906188011169434, 2.125150680541992, 19.388914108276367)