In [26]:
import torch

In [27]:
units=torch.tensor([
    [200,120],
    [240,130],
    [400,120]
])

In [28]:
units.shape

torch.Size([3, 2])

In [29]:
units.dtype

torch.int64

In [30]:
units.device

device(type='cpu')

In [31]:
units.view(-1)

tensor([200, 120, 240, 130, 400, 120])

In [32]:
units[2,1]=289
units

tensor([[200, 120],
        [240, 130],
        [400, 289]])

In [33]:
torch.rand(3,4)

tensor([[0.9363, 0.7601, 0.2054, 0.3659],
        [0.3298, 0.0496, 0.6824, 0.5788],
        [0.2019, 0.7287, 0.4134, 0.9644]])

In [34]:
torch.rand(3,4)

tensor([[0.8812, 0.3056, 0.7647, 0.4030],
        [0.7405, 0.8927, 0.3665, 0.6510],
        [0.7391, 0.9251, 0.2029, 0.8112]])

In [35]:
material_cost=torch.tensor(10,requires_grad=True,dtype=torch.float16)
labor_cost=torch.tensor(5,requires_grad=True,dtype=torch.float16)

total_cost=3*material_cost**2+5*labor_cost+100
total_cost

tensor(425., dtype=torch.float16, grad_fn=<AddBackward0>)

In [36]:
total_cost.backward()
material_cost.grad,labor_cost.grad

(tensor(60., dtype=torch.float16), tensor(5., dtype=torch.float16))

In [37]:
x=torch.tensor([1,2,3],requires_grad=True,dtype=torch.float16)
y=2*x**3+7
y

tensor([ 9., 23., 61.], dtype=torch.float16, grad_fn=<AddBackward0>)

In [38]:
result=y.sum()
result.backward()

In [39]:
#6x^2
x.grad

tensor([ 6., 24., 54.], dtype=torch.float16)

tensor(93., dtype=torch.float16, grad_fn=<SumBackward0>)