In [2]:
import torch

In [3]:
torch.tensor(9)

tensor(9)

In [4]:
revenue=torch.tensor([100,50,60,70])
revenue

tensor([100,  50,  60,  70])

In [5]:
revenue[:3]

tensor([100,  50,  60])

In [6]:
q1=torch.tensor([
    [100,50,60],
    [100,50,70],
    [70,80,80]
])

q2=torch.tensor([
    [100,80,60],
    [190,50,70],
    [170,80,80]
])

In [7]:
q1+q2

tensor([[200, 130, 120],
        [290, 100, 140],
        [240, 160, 160]])

In [8]:
q2-q1

tensor([[  0,  30,   0],
        [ 90,   0,   0],
        [100,   0,   0]])

In [9]:
(q2-q1)*100/q1

tensor([[  0.0000,  60.0000,   0.0000],
        [ 90.0000,   0.0000,   0.0000],
        [142.8571,   0.0000,   0.0000]])

In [10]:
torch.matmul(q1,q2)

tensor([[29700, 15300, 14300],
        [31400, 16100, 15100],
        [35800, 16000, 16200]])

In [11]:
q1.t()

tensor([[100, 100,  70],
        [ 50,  50,  80],
        [ 60,  70,  80]])

In [15]:
if torch.cuda.is_available():
    device=torch.device("cuda")
else:
    device=torch.device("cpu") 

device



device(type='cuda')

In [16]:
#simulating customer data wiht 1 million customers

customer_data=torch.rand(1_000_000,3,device=device)
customer_data


tensor([[0.8660, 0.0752, 0.2030],
        [0.1632, 0.1162, 0.4422],
        [0.4470, 0.7199, 0.9816],
        ...,
        [0.5844, 0.5343, 0.1123],
        [0.0159, 0.6865, 0.4729],
        [0.7655, 0.6535, 0.8389]], device='cuda:0')

In [21]:
customer_data[:,1]

tensor([0.0752, 0.1162, 0.7199,  ..., 0.5343, 0.6865, 0.6535], device='cuda:0')

In [22]:
high_spending_cutomers=customer_data[customer_data[:,1]>0.5]
high_spending_cutomers

tensor([[0.4470, 0.7199, 0.9816],
        [0.3253, 0.8105, 0.1232],
        [0.0412, 0.6876, 0.4264],
        ...,
        [0.5844, 0.5343, 0.1123],
        [0.0159, 0.6865, 0.4729],
        [0.7655, 0.6535, 0.8389]], device='cuda:0')

In [24]:
high_spending_cutomers.shape

torch.Size([500072, 3])

In [25]:
high_spending_cutomers.to('cpu')

tensor([[0.4470, 0.7199, 0.9816],
        [0.3253, 0.8105, 0.1232],
        [0.0412, 0.6876, 0.4264],
        ...,
        [0.5844, 0.5343, 0.1123],
        [0.0159, 0.6865, 0.4729],
        [0.7655, 0.6535, 0.8389]])