# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [2]:
#1 Create a PyTorch Tensor from the following inventory data
inventory=torch.tensor(
    [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]
)
inventory

tensor([[12, 15, 10,  0,  5],
        [10,  8,  7,  5,  4],
        [20, 10, 15,  5,  2]])

In [8]:
#2 Find the total inventory for each item across all days
inventory_sum=inventory.sum(dim=0)
inventory_sum

tensor([42, 33, 32, 10, 11])

In [13]:
#3 Find the average inventory per day
avg_inventory=inventory.float().mean(dim=1)
avg_inventory

tensor([14.0000, 11.0000, 10.6667,  3.3333,  3.6667])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [32]:
#1 Simulate this data using PyTorch's Random Functions
rand_tensor1=torch.randint(50,100,(24,))
rand_tensor1

tensor([75, 62, 92, 67, 93, 95, 54, 81, 79, 97, 62, 65, 96, 96, 51, 89, 64, 65,
        93, 62, 69, 53, 70, 87])

In [34]:
rand_tensor2=torch.randint(50,200,(24,))
rand_tensor2


tensor([ 68, 182, 152, 185, 196, 147, 172, 179, 143,  53,  58,  72, 169, 152,
         53, 180, 192, 112, 146, 162, 114, 104, 197, 150])

In [36]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
total_vehicle1=rand_tensor1.sum(dim=0)
total_vehicle2=rand_tensor2.sum(dim=0)

print(
    total_vehicle1,total_vehicle2)

tensor(1817) tensor(3338)


In [40]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
total_add=rand_tensor1+rand_tensor2
total_add

tensor([143, 244, 244, 252, 289, 242, 226, 260, 222, 150, 120, 137, 265, 248,
        104, 269, 256, 177, 239, 224, 183, 157, 267, 237])



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [43]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
matrix=torch.randint(100,200,(3,3))
matrix

tensor([[155, 101, 154],
        [104, 195, 184],
        [157, 161, 164]])

In [44]:
#2 Find the row-wise and column-wise maximum scores
row_max=matrix.max(dim=1)
col_max=matrix.max(dim=0)
print(row_max,col_max)

torch.return_types.max(
values=tensor([155, 195, 164]),
indices=tensor([0, 1, 2])) torch.return_types.max(
values=tensor([157, 195, 184]),
indices=tensor([2, 1, 1]))


In [46]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
transposed=matrix.t()
transposed

tensor([[155, 104, 157],
        [101, 195, 161],
        [154, 184, 164]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [54]:
#1 Use PyTorch to compute 'y' for x = 4

x=torch.tensor(4.0,requires_grad=True)
x
y=2*x**3+5*x**2-3*x+7
y

tensor(203., grad_fn=<AddBackward0>)

In [55]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward(retain_graph=True)


In [57]:
gradient=x.grad
gradient

tensor(133.)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [ ]:
'''
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])
'''

In [61]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
camera1=torch.tensor([
    [1,2],[3,4]
])
camera2=torch.tensor([
    [5,6] , [7,8]
])
multiplication=camera1*camera2
print(multiplication)

tensor([[ 5, 12],
        [21, 32]])


In [62]:
#2 Compute Dot Product of the two matrices
matmul_prod=torch.matmul(camera1,camera2)
matmul_prod

tensor([[19, 22],
        [43, 50]])

In [66]:
det1=torch.det(camera1.float())
det2=torch.det(camera2.float())

print(det1,det2)

tensor(-2.) tensor(-2.0000)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [72]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(1.0,requires_grad=True)

x=torch.tensor([
    1.0,2.0,3.0,4.0
],requires_grad=True)

print(w)
print(b)
print(x)

tensor(2., requires_grad=True)
tensor(1., requires_grad=True)
tensor([1., 2., 3., 4.], requires_grad=True)


In [73]:
#2 Compute tensors for y

y=w*x+b
y


tensor([3., 5., 7., 9.], grad_fn=<AddBackward0>)



---

